[project]
name = "sysrepo"
make_archive_script = "distro/scripts/make-archive.sh"

[upstream]
archive_url = "https://github.com/sysrepo/sysrepo/archive/v{{ version }}.tar.gz"
version_script = "distro/scripts/upstream-version.sh"

[apkg]
compat = 1
