INSTALLER_DIR="/home/user/PureSoftware/MP_3.0"
INSTALLER_BIN=$INSTALLER_DIR/bin/
INSTALLER_LIB=$INSTALLER_DIR/lib/
  
export PATH="$INSTALLER_BIN:$PATH"
export LD_LIBRARY_PATH="$INSTALLER_LIB:$LD_LIBRARY_PATH"
export C_INCLUDE_PATH="$INSTALLER_DIR/include/:$C_INCLUDE_PATH"
